import playwright from 'playwright-extra';
import stealthPlugin from 'puppeteer-extra-plugin-stealth';
import { GoogleGenerativeAI } from '@google/generative-ai';
import Imap from 'node-imap';
import { simpleParser } from 'mailparser';

// Stealth plugin activate karo taaki koi detect na kar sake
const stealth = stealthPlugin();
playwright.chromium.use(stealth);

// ================= MASTER CONFIGURATION =================
const CONFIG = {
    user: 'sarthaksingh2010ss@gmail.com',
        pass: '@21sar21',
            appPass: 'hlwm rwsj udsw jswj',
                geminiKey: 'AIzaSyDj7qbttjZrITf4DvYCFiUWTBiOtIeBY7Y',
                    apiControl: 'https://lovable.app'
                    };

                    const genAI = new GoogleGenerativeAI(CONFIG.geminiKey);
                    const aiModel = genAI.getGenerativeModel({ model: "gemini-1.5-pro" }); // Pro version for extreme logic

                    // 1. ADVANCED GMAIL OTP ENGINE (Full Auto)
                    async function fetchOTP() {
                        return new Promise((resolve, reject) => {
                                const imapConn = new Imap({ user: CONFIG.user, password: CONFIG.appPass, host: 'imap.gmail.com', port: 993, tls: true });
                                        imapConn.once('ready', () => {
                                                    imapConn.openBox('INBOX', false, (err, box) => {
                                                                    const f = imapConn.seq.fetch(`${box.messages.total}:*`, { bodies: '' });
                                                                                    f.on('message', msg => msg.on('body', stream => simpleParser(stream, (e, p) => {
                                                                                                        const otp = p.text.match(/\d{6}/);
                                                                                                                            if (otp) { imapConn.end(); resolve(otp[0]); }
                                                                                                                                            })));

                                                                                                                                                        });
                                                                                                                                                                });
                                                                                                                                                                        imapConn.once('error', reject);
                                                                                                                                                                                imapConn.connect();
                                                                                                                                                                                        setTimeout(() => { imapConn.end(); reject('OTP_TIMEOUT'); }, 45000);
                                                                                                                                                                                            });
                                                                                                                                                                                            }

                                                                                                                                                                                            // 2. AI SEMANTIC VISION (Page ko dekh kar faisla lena)
                                                                                                                                                                                            async function aiAutonomousDecision(page, task) {
                                                                                                                                                                                                const screenshot = await page.screenshot({ fullPage: false });
                                                                                                                                                                                                    const result = await aiModel.generateContent([
                                                                                                                                                                                                            `Objective: ${task}.
                                                                                                                                                                                                                     Instructions: Scan the screenshot. Find the target button/input. 
                                                                                                                                                                                                                              Analyze security, bypass captchas, and return ONLY a JSON object: {"selector": "CSS_PATH", "action": "CLICK/TYPE", "value": "text_if_any", "confidence": 0-100}`,
                                                                                                                                                                                                                                      { inlineData: { data: screenshot.toString('base64'), mimeType: 'image/png' } }
                                                                                                                                                                                                                                          ]);
                                                                                                                                                                                                                                              return JSON.parse(result.response.text().replace(/```json|```/g, ""));
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                              // 3. THE ULTIMATE EXECUTION ENGINE (24/7)
                                                                                                                                                                                                                                              async function runBrahmastra() {
                                                                                                                                                                                                                                                  const browser = await playwright.chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
                                                                                                                                                                                                                                                      const context = await browser.newContext({
                                                                                                                                                                                                                                                              viewport: { width: 1920, height: 1080 },
                                                                                                                                                                                                                                                                      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'
                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                              const page = await context.newPage();

                                                                                                                                                                                                                                                                                  let currentTarget = "";

                                                                                                                                                                                                                                                                                      console.log("🕉️ BRAHMASTRA INITIATED: JSR AI is now fully Autonomous.");

                                                                                                                                                                                                                                                                                          while (true) {
                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                              // Lovable Chat se master ka order lena
                                                                                                                                                                                                                                                                                                                          const cmd = await fetch(CONFIG.apiControl).then(r => r.json()).catch(() => ({ url: currentTarget, task: "autonomous scan" }));

                                                                                                                                                                                                                                                                                                                                      if (cmd.url && cmd.url !== currentTarget) {
                                                                                                                                                                                                                                                                                                                                                      currentTarget = cmd.url;
                                                                                                                                                                                                                                                                                                                                                                      console.log(`🚀 New Mission: Targeting ${currentTarget}`);
                                                                                                                                                                                                                                                                                                                                                                                      await page.goto(currentTarget, { waitUntil: 'networkidle' });

                                                                                                                                                                                                                                                                                                                                                                                                      // Auto-Login bypass for HackerOne
                                                                                                                                                                                                                                                                                                                                                                                                                      if (currentTarget.includes('hackerone.com')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          await page.type('input[type="email"]', CONFIG.user);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              await page.type('input[type="password"]', CONFIG.pass);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await page.click('button[type="submit"]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log("📥 Waiting for OTP bypass...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await new Promise(r => setTimeout(r, 15000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const otp = await fetchOTP();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await page.type('input[name*="otp"]', otp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await page.click('button[type="submit"]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log("🔓 Access Granted to Master Account.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // AI Vision Action
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const decision = await aiAutonomousDecision(page, cmd.task);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (decision.selector && decision.confidence > 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log(`🎯 AI Action: Performing ${decision.action} on ${decision.selector}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (decision.action === "CLICK") await page.click(decision.selector, { delay: Math.random() * 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (decision.action === "TYPE") await page.fill(decision.selector, decision.value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Self-Healing (Page reload agar kuch na mile)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await page.mouse.move(Math.random()*500, Math.random()*500);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await new Promise(r => setTimeout(r, 20000)); // Every 20 seconds repeat cycle

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log("💎 System Pulse: Standing by for new instructions...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await new Promise(r => setTimeout(r, 10000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      runBrahmastra();
